#!/bin/bash
set -e

NETPLAN_FILE="/etc/netplan/99-dhcp-all.yaml"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)

echo "=== Detecting physical interfaces ==="

# Detect interfaces that are likely physical, excluding virtual ones (docker, tailscale, veth, lo)
INTERFACES=$(ls /sys/class/net | grep -E '^(eno|ens|enp|eth)' | grep -vE 'docker|tailscale|veth|lo')

if [ -z "$INTERFACES" ]; then
    echo "No physical interfaces found."
    exit 1
fi

echo "Found physical interfaces:"
echo "$INTERFACES"
echo

# Backup any existing 99-* netplan files
mkdir -p /etc/netplan/backups/$TIMESTAMP
cp /etc/netplan/*.yaml /etc/netplan/backups/$TIMESTAMP/ 2>/dev/null || true
echo "Backed up current netplan configs to /etc/netplan/backups/$TIMESTAMP/"
echo

echo "=== Generating $NETPLAN_FILE ==="

cat <<EOF > "$NETPLAN_FILE"
# This file was generated by set-all-dhcp.sh on $TIMESTAMP
# It overrides cloud-init (50-cloud-init.yaml) to set all detected physical interfaces to DHCP.
network:
  version: 2
  ethernets:
EOF

for IFACE in $INTERFACES; do
cat <<EOF >> "$NETPLAN_FILE"
    $IFACE:
      dhcp4: true
EOF
done

echo
echo "=== New Netplan file content ==="
cat "$NETPLAN_FILE"
echo

echo "=== Applying Netplan ==="
netplan generate
netplan apply

echo
echo "✅ All physical interfaces are now configured for DHCP via $NETPLAN_FILE"
echo "Existing 50-cloud-init.yaml has been safely overridden (not modified)."
